title: LULLDULL
description: "an online sandbox"
baseurl: ""
url: ""
tagline: "an online sandbox"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
    auto_ids: false
paginator: enable
paginate: 10
paginate_path: '/blog/page:num/'
permalink: /blog/:categories/:year/:title/