title: lulldull
description: "lulldull"
baseurl: ""
url: ""
tagline: "REFERENCE REPOSITORY"
category: ""
collections_dir: projects

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
    auto_ids: false
paginator: enable 
paginate: 100
paginate_path: '/blog/page:num/'
permalink: /blog/:categories/:year/:title/