title: lulldull
description: "lulldull"
baseurl: ""
url: ""
tagline: "REFERENCE REPOSITORY"
category: ""
collections_dir: projects

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
    auto_ids: false
paginator: enable 
paginate: 31
paginate_path: '/page:num/'
permalink: /:year/:title/

# pagination:
#   trail: 
#     before: 2 # The number of links before the current page
#     after: 2  # The number of links after the current page