title: LULLDULL
description: "sandbox"
baseurl: ""
url: ""
tagline: "sandbox"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
    auto_ids: false
paginator: disable
paginate: 200
paginate_path: '/page:num/'
permalink: /:categories/:year/:title/




